//	 Artist - SongName											  Start	 Delay	 FileName																				YouTube id
var songs = [
	["4 Non Blondes - What's Up?"									,0	,1.20	,'6NXnxTNIWkc'],
	["AC/DC - Back In Black"										,0	,4.40	,'pAgnJDJN4VA'],
	["Alice Cooper - Poison"										,0	,2.00	,'Qq4j1LtCdww'],
	["Bloodhound Gang - The Bad Touch"								,0	,20.40	,'xat1GVnl8-k'],
	["Bikini - Közeli helyeken"										,0	,2.00	,'BItlRe5whfo'],
	["Billy Idol - White Wedding"									,0	,2.00	,'AAZQaYKZMTI'],
	["The Cure - Boys Don't Cry"									,0	,10.9	,'9GkVhgIeGJQ'],
	["The Cure - Just Like Heaven"									,0	,10.5	,'n3nPiBai66M'],	//different versions
	["The Cranberries - Zombie"										,0	,12.50	,'6Ejga4kJUts'],
	["Def Leppard - Pour some sugar on me"							,0	,2.0	,'0UIB9Y4OFPs'],
	["Dire Straites - Money For Nothing"							,0	,2.0	,'wTP2RUD_cL0'],
	["Europe - The Final Countdown"									,5	,15.10	,'9jK-NcRmVcw'],
	["Green Day - American Idiot"									,14	,2.00	,'Ee_uujKuJMI'],
	["Green Day - Basket Case"										,14	,2.00	,'NUTGr5t3MoY'],
	["Green Day - Boulevard Of Broken Dreams"						,25	,2.00	,'Soa3gO7tL-c'],
	["Go Betty Go - C'mon"											,0	,2.70	,'7iZhs-p_7Wo'],
	["Guano Apes - Open Your Eyes"									,0	,2.00	,'UNo2-viKfW8'],
	["István a király - Szállj fel szabad madár"					,0.1,12.00	,'FFfxEflFMOQ'],
	["Joan Jett & the Blackhearts - I Hate Myself For Loving You"	,0	,6.15	,'bpNw7jYkbVc'],
	["Joan Jett - I love Rock n Roll"								,28	,1.40	,'xL5spALs-eA'],
	["Joey Ramone - What a Wonderful World"							,41	,2.80	,'8IoO5nkxT_4'],
	["Judas Priest - Breaking the Law"								,3	,11.10	,'L397TWLwrUU'],
	["My Chemical Romance - Planetary (GO!)"						,0	,9.00	,'UvfNmXbVHi4'],
	["My Chemical Romance - Welcome to the Black Parade"			,0	,11.50	,'RRKJiM9Njr8'],
	["Nickelback - Rockstar"										,0	,12.00	,'DmeUuoxyt_E'],
	["Nirvana - Smells Like Teen Spirit"							,0	,2.50	,'hTWKbfoikeg'],
	["The Offspring - Pretty Fly (For A White Guy)"					,0.1,11.00	,'QtTR-_Klcq8'],
	["Pink Floyd - Comfortably Numb"								,20	,2.00	,'zOyk5qnamjc'],
	["R.E.M. - Losing My Religion"									,17	,12.00	,'xwtdhWltSIg'],
	["Republica - Ready to Go"										,0	,26.00	,'JgffRW1fKDk'],	//different versions
	["Roxette - How Do You Do!"										,0	,3.00	,'nx2iLOvP0rM'],
	["Roxette - Listen to Your Heart"								,0	,12.00	,'yCC_b5WHLX0'],
	["Roxette - Sleeping In My Car"									,8.6,4.00	,'S5fn1DfqPfA'],
	["Spin Doctors - Two Princes"									,0	,9.00	,'wsdy_rct6uo'],
	["Steppenwolf - Born to Be Wild"								,7	,12.00	,'egMWlD3fLJ8'],
	["Survivor - Eye of the Tiger"									,0	,11.70	,'btPJPFnesV4'],
	["Tankcsapda - Adjon az eg"										,0	,6.00	,'6hg9-0b3yWU'],
	["Tankcsapda - Azt Mondom Állj"									,8	,2.00	,'xcY0YVuP6Yk'],
	["Tankcsapda - Ez Az A Ház"										,20	,2.80	,'L0pvTDRQCQk'],
	["Tankcsapda - Mennyország Tourist"								,18	,2.00	,'BJceRTvD9Fo'],
	["Tankcsapda - Nem Kell Semmi"									,43	,2.00	,'WYekSotyFpA'],
	["Tankcsapda - Rock a nevem"									,9	,2.00	,'2xT-zz7YyEs'],
	["Twisted Sister - We're Not Gonna Take It"						,172,11.40	,'V9AbeALNVkk'],
	["Van Halen - Jump"												,0	,3.40	,'SwYN7mTi6HM']
];
